spring:
  cloud:
    azure:
      cosmos:
        uri: ${COSMOS_ENDPOINT}
        database: ${COSMOS_DATABASE_NAME}
      keyvault:
        secret:
          vault-url: ${KEYVAULT_URI}
          property-source-enabled: true
        certificate:
          enabled: false
      eventhubs:
        consumer-group: ${EVENTHUB_CONSUMER_GROUP_NAME}
        event-hub-name: ${EVENTHUB_NAME}
        namespace: ${EVENTHUB_NAMESPACE_NAME}
      servicebus:
        producer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        consumer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        namespace: ${SERVICEBUS_NAMESPACE}
      storage:
        blob:
          account-name: ${STORAGE_ACCOUNT_NAME}
          container-name: ${STORAGE_BLOB_CONTAINER_NAME}
        fileshare:
          enabled: false
management:
  endpoint:
    health:
      show-details: always
  health:
    azure-cosmos:
      enabled: true
