spring:
  cloud:
    azure:
      credential:
        client-id: ${SPRING_CLIENT_ID}
        client-secret: ${SPRING_CLIENT_SECRET}
      profile:
        tenant-id: ${SPRING_TENANT_ID}
      cosmos:
        uri: ${COSMOS_ENDPOINT}
        database: ${COSMOS_DATABASE_NAME}
      keyvault:
        secret:
          vault-url: ${KEYVAULT_URI}
          property-source-enabled: true
        certificate:
          vault-url: ${KEYVAULT_URI}
          enabled: false
      eventhubs:
        consumer-group: ${EVENTHUB_CONSUMER_GROUP_NAME}
        event-hub-name: ${EVENTHUB_NAME}
        namespace: ${EVENTHUB_NAMESPACE_NAME}
      servicebus:
        producer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        consumer:
          queue-name: ${SERVICEBUS_QUEUE_NAME}
        namespace: ${SERVICEBUS_NAMESPACE}
      storage:
        blob:
          account-name: ${STORAGE_ACCOUNT_NAME}
          container-name: ${STORAGE_BLOB_CONTAINER_NAME}
        fileshare:
          enabled: false
